[phase1]
name = "Foundation & Data Ops"

[[phase1.tasks]]
id = 1
name = "Finalize SQLite database structure & integration"
description = "Design and implement the core database schema to store email data and metadata efficiently"
start_date = "2025-04-03"
end_date = "2025-04-09"
assignee = "estebann23"

[[phase1.tasks]]
id = 2
name = "Add full support for other datasets"
description = "Extend data loaders to handle Kaggle & UCI datasets with consistent preprocessing"
start_date = "2025-04-10"
end_date = "2025-04-16"
assignee = "estebann23"

[[phase1.tasks]]
id = 3
name = "Implement data anonymization module"
description = "Create a system to detect and scrub personally identifiable information from all datasets"
start_date = "2025-04-03"
end_date = "2025-04-09"
assignee = "DuckBloodJ"

[[phase1.tasks]]
id = 4
name = "Expand and test NER with HuggingFace models"
description = "Implement and evaluate HuggingFace NER models as an upgrade from spaCy"
start_date = "2025-04-10"
end_date = "2025-04-16"
assignee = "DuckBloodJ"

[[phase1.tasks]]
id = 5
name = "Add NER label mapping to DB"
description = "Store and categorize named entities (person, company, date, etc.) in the database"
start_date = "2025-04-10"
end_date = "2025-04-16"
assignee = "DuckBloodJ"

[[phase1.tasks]]
id = 6
name = "Add parallel loading for very large datasets"
description = "Optimize data loading pipeline to handle datasets with more than 10k emails"
start_date = "2025-04-10"
end_date = "2025-04-16"
assignee = "estebann23"

[[phase1.tasks]]
id = 7
name = "Build CLI or GUI interface for dataset loading"
description = "Create a simple interface for importing and inspecting email datasets"
start_date = "2025-04-03"
end_date = "2025-04-09"
assignee = "NoamFav"

[phase2]
name = "Advanced NLP Models"

[[phase2.tasks]]
id = 8
name = "Upgrade text classification to use BERT/RoBERTa"
description = "Implement transformer-based models for improved classification accuracy"
start_date = "2025-04-08"
end_date = "2025-04-14"
assignee = "GiorgosdeJonge"

[[phase2.tasks]]
id = 9
name = "Compare RoBERTa vs current classifier"
description = "Benchmark performance differences between baseline and transformer models"
start_date = "2025-04-15"
end_date = "2025-04-21"
assignee = "GiorgosdeJonge"

[[phase2.tasks]]
id = 10
name = "Implement tone classification"
description = "Add capability to detect formal, casual, and sarcastic tones in emails"
start_date = "2025-04-22"
end_date = "2025-04-28"
assignee = "GiorgosdeJonge"

[[phase2.tasks]]
id = 11
name = "Train emotion classification beyond TextBlob"
description = "Implement pretrained emotion BERT models for more nuanced sentiment analysis"
start_date = "2025-04-29"
end_date = "2025-05-07"
assignee = "GiorgosdeJonge"

[[phase2.tasks]]
id = 12
name = "Replace/augment TextBlob with VADER or FinBERT"
description = "Enhance sentiment analysis with specialized models for financial content"
start_date = "2025-04-29"
end_date = "2025-05-07"
assignee = "GiorgosdeJonge"

[[phase2.tasks]]
id = 13
name = "Add zero-shot classification"
description = "Implement BART or GPT-based classification for flexible category detection"
start_date = "2025-04-15"
end_date = "2025-04-21"
assignee = "RemiHeijmans"

[[phase2.tasks]]
id = 14
name = "Fine-tune a small GPT model for smart reply"
description = "Train a specialized model for generating contextually appropriate email replies"
start_date = "2025-04-22"
end_date = "2025-04-28"
assignee = "RemiHeijmans"

[[phase2.tasks]]
id = 15
name = "Build context windowing for threaded replies"
description = "Create system to maintain conversation context for multi-email threads"
start_date = "2025-04-29"
end_date = "2025-05-07"
assignee = "RemiHeijmans"

[[phase2.tasks]]
id = 16
name = "Implement extractive summarizer"
description = "Add BERTSUM or TextRank for key sentence extraction from emails"
start_date = "2025-04-22"
end_date = "2025-04-28"
assignee = "RemiHeijmans"

[[phase2.tasks]]
id = 17
name = "Implement abstractive summarizer"
description = "Add T5 or Pegasus models for generating natural language summaries"
start_date = "2025-04-29"
end_date = "2025-05-07"
assignee = "RemiHeijmans"

[[phase2.tasks]]
id = 18
name = "Build a summary method selector"
description = "Create logic to choose optimal summarization technique based on email type/length"
start_date = "2025-05-01"
end_date = "2025-05-07"
assignee = "RemiHeijmans"

[[phase2.tasks]]
id = 19
name = "Add summarization output post-processing"
description = "Implement deduplication and sentence scoring to improve summary quality"
start_date = "2025-05-01"
end_date = "2025-05-07"
assignee = "RemiHeijmans"

[phase3]
name = "Backend & Pipeline"

[[phase3.tasks]]
id = 20
name = "Modularize pipeline"
description = "Restructure code into distinct modules: Loader → NER → Tone → Classifier → Summary → Reply"
start_date = "2025-04-15"
end_date = "2025-04-21"
assignee = "NoamFav"

[[phase3.tasks]]
id = 21
name = "Allow modular switching between model versions"
description = "Enable runtime selection between baseline and advanced models"
start_date = "2025-04-22"
end_date = "2025-04-28"
assignee = "NoamFav"

[[phase3.tasks]]
id = 22
name = "Add config system for thresholds"
description = "Implement configuration for tuning urgency, tone, and other classification parameters"
start_date = "2025-04-29"
end_date = "2025-05-05"
assignee = "NoamFav"

[[phase3.tasks]]
id = 23
name = "Add async task handling"
description = "Implement Celery or multiprocessing queue for parallel email processing"
start_date = "2025-05-01"
end_date = "2025-05-07"
assignee = "NoamFav"

[[phase3.tasks]]
id = 24
name = "Wrap email processing in a backend API"
description = "Create REST API with Flask or FastAPI to expose processing functionality"
start_date = "2025-05-03"
end_date = "2025-05-10"
assignee = "NoamFav"

[[phase3.tasks]]
id = 25
name = "Add full search engine over metadata"
description = "Implement indexing and search capabilities for email content and metadata"
start_date = "2025-04-29"
end_date = "2025-05-05"
assignee = "estebann23"

[[phase3.tasks]]
id = 26
name = "Implement fuzzy search + semantic matching"
description = "Add advanced search features with approximate string matching and semantic similarity"
start_date = "2025-05-01"
end_date = "2025-05-07"
assignee = "estebann23"

[[phase3.tasks]]
id = 27
name = "Enable advanced filters in search"
description = "Add filtering by NER tags, sentiment scores, and temporal data"
start_date = "2025-05-03"
end_date = "2025-05-10"
assignee = "estebann23"

[[phase3.tasks]]
id = 28
name = "Log predictions in DB"
description = "Store all system predictions with metadata for analysis and improvement"
start_date = "2025-05-03"
end_date = "2025-05-10"
assignee = "estebann23"

[[phase3.tasks]]
id = 29
name = "Write tests for each pipeline stage"
description = "Create comprehensive unit and integration tests for all components"
start_date = "2025-04-03"
end_date = "2025-04-16"
assignee = "OctavianUM"

[[phase3.tasks]]
id = 30
name = "Add email polling system"
description = "Implement scheduler to simulate real-time email processing with cron jobs"
start_date = "2025-05-03"
end_date = "2025-05-10"
assignee = "estebann23"

[phase4]
name = "GUI (C++) & Usability"

[[phase4.tasks]]
id = 31
name = "Design email inbox mock UI"
description = "Create Qt or ImGui-based interface mimicking a standard email client"
start_date = "2025-04-17"
end_date = "2025-04-23"
assignee = "NoamFav"

[[phase4.tasks]]
id = 32
name = "Display category, tone, urgency with visual tags"
description = "Implement visual indicators foremail attributes in the UI"
start_date = "2025-04-24"
end_date = "2025-04-30"
assignee = "OctavianUM"

[[phase4.tasks]]
id = 33
name = "Show summary and smart reply suggestions"
description = "Display generated summaries and reply options within the email view"
start_date = "2025-05-01"
end_date = "2025-05-07"
assignee = "NoamFav"

[[phase4.tasks]]
id = 34
name = "Add interactive email thread visualizer"
description = "Create collapsible tree view for email conversation threads"
start_date = "2025-04-24"
end_date = "2025-04-30"
assignee = "OctavianUM"

[[phase4.tasks]]
id = 35
name = "Include filters and search"
description = "Add search bar and dropdown filters for email navigation"
start_date = "2025-05-01"
end_date = "2025-05-07"
assignee = "OctavianUM"

[[phase4.tasks]]
id = 36
name = "Add threshold adjustment sliders"
description = "Create interactive controls to tweak confidence thresholds for classifications"
start_date = "2025-05-08"
end_date = "2025-05-14"
assignee = "OctavianUM"

[[phase4.tasks]]
id = 37
name = "Allow editing + approving smart replies"
description = "Enable users to modify and approve generated replies before sending"
start_date = "2025-05-08"
end_date = "2025-05-14"
assignee = "OctavianUM"

[[phase4.tasks]]
id = 38
name = "Build inbox analytics view"
description = "Create dashboard showing email statistics and category distributions"
start_date = "2025-05-08"
end_date = "2025-05-14"
assignee = "NoamFav"

[[phase4.tasks]]
id = 39
name = "Support CSV import/export"
description = "Add functionality to import/export data for external testing and analysis"
start_date = "2025-05-01"
end_date = "2025-05-07"
assignee = "DuckBloodJ"

[[phase4.tasks]]
id = 40
name = "Connect GUI to backend predictions"
description = "Integrate the UI with the processing backend via API or direct bindings"
start_date = "2025-05-08"
end_date = "2025-05-14"
assignee = "NoamFav"

[phase5]
name = "Evaluation & Study"

[[phase5.tasks]]
id = 41
name = "Evaluate classifier performance"
description = "Compare metrics between baseline and advanced classification models"
start_date = "2025-05-01"
end_date = "2025-05-07"
assignee = "GiorgosdeJonge"

[[phase5.tasks]]
id = 42
name = "Compare summary quality"
description = "Evaluate summaries using ROUGE/BLEU/METEOR against human benchmarks"
start_date = "2025-05-01"
end_date = "2025-05-07"
assignee = "RemiHeijmans"

[[phase5.tasks]]
id = 43
name = "Evaluate reply generation"
description = "Compare quality of AI-generated replies against human-written ones"
start_date = "2025-05-08"
end_date = "2025-05-14"
assignee = "RemiHeijmans"

[[phase5.tasks]]
id = 44
name = "Run user study"
description = "Conduct formal study measuring efficiency, satisfaction, and preferences"
start_date = "2025-05-08"
end_date = "2025-05-14"
assignee = "OctavianUM"

[[phase5.tasks]]
id = 45
name = "Analyze user feedback"
description = "Process Likert scale ratings and qualitative feedback from users"
start_date = "2025-05-08"
end_date = "2025-05-14"
assignee = "OctavianUM"

[[phase5.tasks]]
id = 46
name = "Track time-to-respond"
description = "Measure response time improvements with and without AI assistance"
start_date = "2025-05-01"
end_date = "2025-05-07"
assignee = "DuckBloodJ"

[[phase5.tasks]]
id = 47
name = "Log emotional tone variance"
description = "Analyze emotional tone distribution across different datasets"
start_date = "2025-05-08"
end_date = "2025-05-14"
assignee = "GiorgosdeJonge"

[[phase5.tasks]]
id = 48
name = "Evaluate usefulness of emotion/tone"
description = "Assess correlation between tone detection accuracy and user satisfaction"
start_date = "2025-05-08"
end_date = "2025-05-14"
assignee = "GiorgosdeJonge"

[[phase5.tasks]]
id = 49
name = "Write experiment results"
description = "Compile all evaluation metrics and findings into final report"
start_date = "2025-05-08"
end_date = "2025-05-14"
assignee = "GiorgosdeJonge"

[[phase5.tasks]]
id = 50
name = "Prepare interactive demo"
description = "Create polished demonstration for final presentation"
start_date = "2025-05-08"
end_date = "2025-05-14"
assignee = "NoamFav"

[phase6]
name = "Finalization Phase"

[[phase6.tasks]]
id = 51
name = "System integration and testing"
description = "Comprehensive integration of all components and system-wide testing"
start_date = "2025-05-15"
end_date = "2025-05-21"
assignee = "estebann23"

[[phase6.tasks]]
id = 52
name = "Bug fixes and performance optimization"
description = "Resolve issues and improve system performance"
start_date = "2025-05-22"
end_date = "2025-05-28"
assignee = "DuckBloodJ"

[[phase6.tasks]]
id = 53
name = "Final documentation and code cleanup"
description = "Complete comprehensive documentation and refine codebase"
start_date = "2025-05-29"
end_date = "2025-06-04"
assignee = "DuckBloodJ"

[[phase6.tasks]]
id = 54
name = "Demo preparation and polish"
description = "Refine demo materials and ensure presentation readiness"
start_date = "2025-06-05"
end_date = "2025-06-09"
assignee = "NoamFav"

[[phase6.tasks]]
id = 55
name = "Final presentation and delivery"
description = "Deliver final presentation and complete project handover"
start_date = "2025-06-10"
end_date = "2025-06-13"
assignee = "RemiHeijmans"
